export const ADD_INGREDIENT = 'ADD_INGREDIENT';

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const ADD_RECIPE = 'ADD_RECIPE';

export const FETCH_RECIPES = 'FETCH_RECIPES';

export const SET_RECIPES = 'SET_RECIPES';
